[mcp_servers.laravel-boost]
command = "php"
args = ["artisan", "boost:mcp"]
cwd = "C:\\Users\\jadeg\\Documents\\Capstone\\marriott"

[mcp_servers.shadcn]
command = "npx"
args = ["shadcn@latest", "mcp"]
cwd = "C:\\Users\\jadeg\\Documents\\Capstone\\marriott"
